// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dulmczxulhevhxwjyaze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1bG1jenh1bGhldmh4d2p5YXplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MjEyOTQsImV4cCI6MjA2MzQ5NzI5NH0.A7F40pP2ozq0crxe-YnvSFZvIWth1ZUXJGM6L3_f-5w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});